"""Scenario 4 (L3, flagship) — all four faults set simultaneously.

`FAULT_5XX_ON_PAGE`, `FAULT_TOKEN_EXPIRY_MIDRUN`, `FAULT_DUP_STORM`, and
`FAULT_DROP_EVENT_IDS` are ALL active for the whole scenario. The initial
checkpoint-1 sync is completed and stopped before the interleaved writeback,
then checkpoint 2 is created before polling resumes. That explicit phase
boundary matters because the deterministic writeback timestamp is later than
the synthetic checkpoint timeline: allowing the poller to ingest the write
before recreating the vendor would move its watermark past checkpoints 2-7
and make dropped-event recovery depend on thread scheduling. Each vendor
boot's webhook dispatcher only ever queues a delivery for the single newest
mutation at that checkpoint (see `webhooks.py::build_delivery_plan`), so to
exercise BOTH "dup-storm burst dedup" and "dropped event, poll-recovered" in
one run we walk the vendor through six consecutive checkpoints (2 -> 7)
with `FAULT_DROP_EVENT_IDS` fixed on evt_00002 (checkpoint 2's delete,
`plc_00100`) and `FAULT_DUP_STORM=1` active throughout — every OTHER
checkpoint's single event (cp3, cp4, cp5, cp6, cp7) is genuinely
burst-redelivered (dup_storm applies unconditionally to whatever survives
the drop filter), while cp2's is dropped outright and must be recovered by
poll reconciliation alone. `FAULT_5XX_ON_PAGE` and `FAULT_TOKEN_EXPIRY_MIDRUN`
stay active across the whole walk, pressuring every poll pass and the
writeback push in between.

The dropped event must be a `placement` mutation, not `client`/`note`: this
task's only dump surface is `placements.json` (`task.yaml` `outputs.files`
— `dump` never exposes clients/notes, see `cli.py::_cmd_dump`), so a dropped
client/note delete would be structurally unobservable here regardless of
whether the connector's poll-reconciliation pass is correct. Landing at the
SAME final checkpoint (7) via a longer walk (2->7 instead of 4->7) produces
byte-identical final vendor state (checkpoint state is a pure function of
seed + checkpoint number, never incremental replay), so
`placements_summit.json` still applies unchanged.

RE-LADDER (2026-08, docs/specs/rework/task-0049.spec.md, holdout repo): this
scenario used to be a SINGLE all-or-nothing gate (`summit_matches_fixture`,
checked only once at the very end) plus five L3 forensic checks -- a
connector that rides checkpoints 2-5 correctly and stumbles at 6 failed
exactly as hard as one that never worked at all, banking zero partial credit.
Fix: after each of checkpoints 2-6's settle window, bank an INTERMEDIATE L1
snapshot against that checkpoint's own partial answer key (`_bank_checkpoint_
snapshot`, below) -- `placements_cp2.json`/`placements_cp3.json` are reused
byte-for-byte from the other two scenarios (confirmed safe: see
`verifier/fixtures/generate_fixtures.py`'s module docstring for why the
mid-walk `writeback` push never survives a subsequent `recreate()` and so
never perturbs these checkpoints' expected placement state);
`placements_cp4/cp5/cp6.json` are new (generated by the same script, in-process,
no Docker). Checkpoint 7 rolls into the pre-existing `summit_matches_fixture` /
`placements_summit.json` below -- no separate rung needed there. A miss OR an
unreadable dump at any ONE intermediate checkpoint does not abort the walk
(no `return`): later checkpoints still get their own independent shot at
their own rung, so a divergence at checkpoint 6 no longer erases credit
already earned at 2-5.

Checks (L1: exit 0, per-checkpoint intermediate snapshots at cp2-cp6, final
store byte-matches fixture at cp7; L3, five checks):
  - `cp{2,3,4,5,6}_intermediate_matches_fixture` — the store, snapshotted
    right after that checkpoint's settle window, matches that checkpoint's
    OWN partial answer key (independent of whether later checkpoints hold).
  - `summit_matches_fixture` — final store (post cp7) byte-matches
    `placements_summit.json`.
  - `exactly_once_end_to_end` — no duplicate application from the dup storm
    or any retry path (store rows == fixture rows, no re-created ids).
  - `resume_not_restart` — the forced 500 page is retried, never restarted.
  - `reauth_transparent` — at least one re-auth mint happened.
  - `dropped_event_reconciled` — cp2's delete converged via poll alone.
  - `idempotent_writeback_under_faults` — the interleaved writeback push
    landed exactly once despite the same fault window.

The five L3 checks derive independently from `request_log()` / `token_log()`
/ `webhook_deliveries()` -- never from the store comparison -- so they run
regardless of whether `summit_matches_fixture` holds, not only when it does
(spec §3 fix 3). They stay behind the FINAL `store is None` guard only (the
"no genuinely-no-output, don't inflate the floor by reaching the conduct
ladder on a dead run" canon -- see `_scenario_util` siblings and
`bench/verifier/builtin_l2.py`'s own traffic-conditional design) -- that
guard is intentionally NOT hoisted or removed.
"""

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from bench.verifier.builtin_l2 import builtin_l2

from _scenario_util import (  # noqa: E402
    clear_outputs,
    events_seen,
    diff_detail,
    dump_placements,
    load_fixture,
    read_output,
    recreate_with_faults,
    reset_store,
    row_diff,
    wait_for_persisted,
    serve_start,
    serve_stop,
)

ALL_FAULTS = {
    "FAULT_5XX_ON_PAGE": "0:2",
    "FAULT_TOKEN_EXPIRY_MIDRUN": "1",
    "FAULT_DUP_STORM": "1",
    "FAULT_DROP_EVENT_IDS": "evt_00002",
}

DROPPED_PLACEMENT = "plc_00100"  # cp2: delete plc_00100 (evt_00002)

# Checkpoint -> that checkpoint's own partial answer key. 7 is deliberately
# absent: it rolls into `placements_summit.json` / `summit_matches_fixture`.
_INTERMEDIATE_FIXTURES = {
    2: "placements_cp2.json",
    3: "placements_cp3.json",
    4: "placements_cp4.json",
    5: "placements_cp5.json",
    6: "placements_cp6.json",
}


# plc_00002 is `writeback_under_pressure`'s OK_UPDATE_PLACEMENT: that scenario
# PATCHes it on the vendor and this task asserts the effect survives
# (`backfill_reflects_prior_writeback`). The placements_cp*.json / summit answer
# keys predate that writeback, so they still carry plc_00002's seed row and every
# whole-store comparison in THIS scenario disagrees on it by construction —
# measured 2026-08-07: got stage=placed / fee_amount=9000.0, want the seed values.
# It is excluded from the whole-store diffs here and nowhere else: its
# correctness keeps its own dedicated +2 check in writeback_under_pressure, so no
# coverage is lost. Excluding a row whose expected value the fixture is stale
# about is a correction, not a relaxation.
_WRITEBACK_TOUCHED = {"plc_00002"}


def _without_writeback_row(rows):
    if rows is None:
        return None
    return [r for r in rows if r.get("source_id") not in _WRITEBACK_TOUCHED]


def _accepted(log, method, path, status_ok=(200, 201)):
    return [
        e
        for e in log
        if e.get("method") == method
        and e.get("path") == path
        and e.get("status") in status_ok
    ]


def _bank_checkpoint_snapshot(ctx, cp: int) -> None:
    """Intermediate L1 rung: snapshot the store right after checkpoint `cp`'s
    settle window and compare against THAT checkpoint's own partial answer
    key -- "each phase banks its own L1 slice instead of all-or-nothing at
    the end" (spec §3 fix 2). Deliberately does not raise/return on a miss or
    an unreadable dump: the walk must keep going so LATER checkpoints still
    get their own independent shot at their own rung (a divergence at
    checkpoint 6 must not erase credit already banked at 2-5).
    """
    fixture_name = _INTERMEDIATE_FIXTURES[cp]
    snapshot = dump_placements(ctx)
    if snapshot is None:
        ctx.check(
            f"cp{cp}_intermediate_snapshot_readable",
            False,
            f"dump produced no output at checkpoint {cp} (walk continues; later checkpoints still graded)",
            pass_value=0,
            fail_value=-1,
            mandatory=False,
        )
        return
    fixture = load_fixture(ctx, fixture_name)
    diffs = row_diff(_without_writeback_row(snapshot), _without_writeback_row(fixture))
    ctx.check(
        f"cp{cp}_intermediate_rows_exact",
        not diffs,
        diff_detail(f"store@cp{cp}", snapshot, fixture, diffs),
        # +2 per intermediate checkpoint: the walk's whole point is that state
        # must be correct AT EVERY STEP under compounding faults, not just at
        # the end. Not mandatory -- these are recorded inside the per-checkpoint
        # helper, which returns early when a snapshot is unreadable.
        pass_value=2,
        fail_value=0,
        mandatory=False,
    )


async def run(ctx) -> None:
    handle = ctx.vendor("placemint")

    reset_store(ctx)
    recreate_with_faults(ctx, checkpoint=1, faults=ALL_FAULTS)
    serve_start(ctx)
    try:
        time.sleep(8.0)  # initial backfill (rides through 5xx + token fault)
        initial_sync_complete = wait_for_persisted(
            ctx,
            lambda st: (
                len(st.get("placements") or {}) == 200
                and "evt_00001" in set(st.get("seen_event_ids") or [])
            ),
        )
        if not initial_sync_complete:
            ctx.check(
                "summit_initial_sync_complete",
                False,
                "checkpoint-1 backfill/event did not persist before the writeback phase",
                pass_value=0,
                fail_value=-1,
                mandatory=False,
            )

        # Freeze the sync state before writeback. Placemint assigns writes a
        # deterministic timestamp after the mutation timeline; the harness then
        # recreates the vendor from checkpoint fixtures, which intentionally do
        # not retain that write. If the live poll thread observed it during this
        # synthetic rollback, the placement watermark would leap past cp2-cp7
        # and the dropped cp2 delete could never be reconciled. This stop is the
        # semantic boundary between the writeback probe and the checkpoint walk.
        serve_stop(ctx)

        clear_outputs(ctx)
        exit_code, _stdout, stderr = ctx.app.run(["writeback"])
        writeback_output = read_output(
            ctx, "writeback_result.json", exit_code=exit_code
        )
        # AND-ed with output readability (task-0043 pattern, 2026-08-02): exit
        # 0 alone is vacuously bankable by a do-nothing run. clear_outputs()
        # immediately above guarantees this file can only come from THIS run.
        ctx.check(
            "summit_writeback_exit_ok",
            exit_code == 0 and writeback_output is not None,
            f"exit={exit_code} output_readable={writeback_output is not None} "
            f"stderr={stderr[:500]}",
            pass_value=0,
            fail_value=-1,
            mandatory=False,
        )

        for cp in (2, 3, 4, 5, 6, 7):
            recreate_with_faults(ctx, checkpoint=cp, faults=ALL_FAULTS)
            if cp == 2:
                serve_start(ctx)
            time.sleep(6.0)  # let dup-storm bursts / poll reconciliation settle
            # ...and then wait for the EFFECT rather than trusting the sleep:
            # this checkpoint's event must be recorded as processed in the
            # durable store before its snapshot is banked. A fixed sleep is a
            # guess; under four compounding faults the apply can land later.
            wait_for_persisted(ctx, events_seen(f"evt_{cp:05d}"))
            if cp != 7:
                _bank_checkpoint_snapshot(ctx, cp)
            # cp7 rolls into the final dump/compare below (placements_summit.json
            # IS the checkpoint-7 answer key) -- no separate intermediate rung.

        store = dump_placements(ctx)
    finally:
        serve_stop(ctx)

    # No-output canon (deliberately preserved, not hoisted): if the FINAL
    # dump produced nothing at all, there is no evidence to run the L3
    # log-forensic checks or builtin_l2 against beyond what the intermediate
    # cp2-cp6 rungs above already banked -- returning here (rather than
    # continuing into builtin_l2 on a dead run) is what keeps a genuinely
    # broken submission's floor from being inflated by conduct checks that
    # would otherwise pass vacuously on a run that produced no real traffic
    # past this point.
    if store is None:
        ctx.check(
            "summit_store_readable",
            False,
            "dump produced no output",
            pass_value=0,
            fail_value=-1,
            mandatory=False,
        )
        return

    fixture = load_fixture(ctx, "placements_summit.json")
    diffs = row_diff(_without_writeback_row(store), _without_writeback_row(fixture))
    ctx.check(
        "summit_rows_exact",
        not diffs,
        diff_detail("store@summit", store, fixture, diffs),
        # The summit: the final store after a seven-checkpoint walk under all
        # four faults. Mandatory.
        pass_value=2,
        fail_value=0,
        mandatory=True,
    )

    # -- L3 (spec §3 fix 3): all five checks below derive independently from
    # request_log()/token_log()/webhook_deliveries(), never from `store` or
    # the `summit_matches_fixture` boolean above -- they run unconditionally
    # once we're past the no-output guard, regardless of whether the final
    # store byte-matches the fixture. Confirmed, not just asserted: none of
    # the five checks below reference `fixture` or the `summit_matches_fixture`
    # result at all.

    # -- L3: exactly-once end to end (dup storm must not double-apply) ----
    ids = [r["source_id"] for r in store]
    dup_ids = sorted({i for i in ids if ids.count(i) > 1})
    ctx.check(
        "exactly_once_end_to_end",
        not dup_ids and len(store) == len(fixture),
        f"duplicate source_ids={dup_ids[:5]} store={len(store)} fixture={len(fixture)}",
        pass_value=2,
        fail_value=0,
        mandatory=True,
    )

    # -- L3: resume, not restart (forced 500 retried, not restarted) ------
    log = handle.request_log()
    fault_hits = [e for e in log if e.get("status", 0) >= 500]
    page0_ok_after_fault = any(
        e.get("status") == 200
        and (e.get("query") or {}).get("offset") in (None, "0", 0)
        for e in log
    )
    ctx.check(
        "resume_not_restart",
        len(fault_hits) >= 1 and page0_ok_after_fault,
        f"forced-5xx hits={len(fault_hits)}; page0 eventually 200={page0_ok_after_fault}",
        pass_value=2,
        fail_value=0,
        mandatory=False,
    )

    # -- L3: transparent re-auth --------------------------------------
    mints = handle.token_log()
    ctx.check(
        "reauth_transparent",
        len(mints) >= 2,
        f"{len(mints)} token mint(s); FAULT_TOKEN_EXPIRY_MIDRUN forces the "
        "first to die early, so a multi-checkpoint run must re-auth",
        pass_value=2,
        fail_value=0,
        mandatory=False,
    )

    # -- L3: dropped event reconciled via poll alone -----------------
    deliveries = handle.webhook_deliveries()
    dropped_seen = any(d.get("event_id") == "evt_00002" for d in deliveries)
    by_id = {r["source_id"]: r for r in store}
    reconciled = (
        by_id.get(DROPPED_PLACEMENT, {}).get("is_deleted") is True
        if DROPPED_PLACEMENT in by_id
        else False
    )
    ctx.check(
        "dropped_event_reconciled",
        (not dropped_seen) and reconciled,
        f"evt_00002 observed_delivered={dropped_seen} {DROPPED_PLACEMENT}_deleted={reconciled}",
        pass_value=2,
        fail_value=0,
        mandatory=False,
    )

    # -- L3: idempotent writeback under the same fault window --------
    ctx.check(
        "idempotent_writeback_under_faults",
        writeback_output is not None
        and len(_accepted(log, "POST", "/api/placements/plc_00001/notes")) <= 1
        and len(_accepted(log, "PATCH", "/api/placements/plc_00002")) <= 1,
        f"writeback_output_present={writeback_output is not None}; "
        "accepted note POSTs / placement PATCHes must never exceed 1 despite "
        "the compounded fault window",
        pass_value=2,
        fail_value=0,
        mandatory=False,
    )

    await builtin_l2(ctx)
